### ISSUE TITLE
ACF premium add-on in public github repo

### ISSUE THREAD

**Issue by elliotcondon** [clarklab/little#1]
Hi @clarklab 

Just wanted to let you know that this public repo contains premium ACF add-ons which violates the terms and conditions for the product.

I'm hoping this is a mistake, but will need to ask you to either make this repo private or remove the ACF premium add-ons from it.

Thanks
Elliot

**Comment by clarklab** [comment]
Doh! Didn't even know this was still here. Pulling it offline now!
